### ISSUE TITLE
Problem with building app.

### ISSUE THREAD

**Issue by wojciechSlodziak** [driftyco/ionic-starter-salesforce#12]
I'm having problems with building app on Android platform.
After downloading fresh app and adding platform i get error after:
**ionic build android**

Error:

C:\workspace\testApp>ionic build android
Running command: "C:\Program Files\nodejs\node.exe" C:\workspace\testApp\hooks\after_prepare\010_add_platform_class.js C:\workspace\testApp
add to body class: platform-android
Running command: cmd "/s /c "C:\workspace\testApp\platforms\android\cordova\build.bat""
ANDROID_HOME=C:\AndroidSDK
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_25
Running: C:\workspace\testApp\platforms\android\gradlew cdvBuildDebug -b C:\workspace\testApp\platforms\android\build.gradle -Dorg.gradle.daemon=true

BUILD FAILED

Total time: 6.985 secs
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\workspace\testApp\platforms\android\settings.gradle' line: 4

* What went wrong:
A problem occurred evaluating settings 'android'.
> A path must be specified!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

C:\workspace\testApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\workspace\testApp\platforms\android\gradlew cdvBuildDebug -b C:\workspace\testApp\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\MyName\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

Other starter apps work for me so it is not problem with my setup.

**Comment by plevie** [comment]
I got the same problem. Could you solve it yet?

**Comment by spartan-1** [comment]
any solution for this ?
